local FFlags = {
    ["DFIntNetworkLatencyTolerance"] = 1,
    ["DFFlagRakNetCalculateApplicationFeedback2"] = true,
    ["FStringRemoteAnimationSmoothingStrategy"] = "ExponentialDecay",
    ["DFIntClientPacketMaxFrameMicroseconds"] = 200,
    ["FIntFontSizePadding"] = 2,
    ["FFlagDebugSkyGray"] = true,
    ["DFIntRakNetNakResendDelayMsMax"] = 100,
    ["DFIntGraphicsOptimizationModeMaxFrameTimeTargetMs"] = 20,
    ["FFlagOptimizeNetworkRouting"] = true,
    ["DFFlagNetworkUseZstdWrapper"] = false,
    ["DFIntRakNetNakResendDelayRttPercent"] = 50,
    ["FFlagDebugGraphicsPreferD3D11FL10"] = true,
    ["DFIntTextureQualityOverride"] = 0,
    ["FFlagDisableFeedbackSoothsayerCheck"] = false,
    ["DFIntPlayerNetworkUpdateRate"] = 60,
    ["FFlagOptimizeServerTickRate"] = true,
    ["DFIntMaxDataPacketPerSend"] = 2147483647,
    ["FFlagEnableInGameMenuControls"] = true,
    ["FIntInterpolationAwareTargetTimeLerpHundredth"] = 110,
    ["DFIntRakNetMtuValue2InBytes"] = 1240,
    ["FFlagEnablePerformanceControlService"] = true,
    ["DFIntRakNetNakResendDelayMs"] = 10,
    ["DFIntMegaReplicatorNetworkQualityProcessorUnit"] = 10,
    ["DFIntInitialAccelerationLatencyMultTenths"] = 1,
    ["DFIntNetworkSchemaCompressionRatio"] = 100,
    ["DFIntPerformanceControlFrameTimeMax"] = 1,
    ["FFlagEnableZstdDictionaryForClientSettings"] = false,
    ["DFIntTaskSchedulerTargetFps"] = 9999,
    ["DFIntMaxAcceptableUpdateDelay"] = 1,
    ["FFlagDebugLargeReplicatorRead"] = true,
    ["DFFlagRakNetDetectRecvThreadOverload"] = true,
    ["FFlagFasterPreciseTime4"] = true,
    ["FFlagRigScaleShouldAffectAnimations"] = true,
    ["DFIntRakNetLoopMs"] = 1,
    ["DFIntMaxProcessPacketsStepsPerCyclic"] = 5000,
    ["DFIntCodecMaxIncomingPackets"] = 100,
    ["DFIntClientPacketHealthyAllocationPercent"] = 20,
    ["FFlagDebugForceFutureIsBrightPhase3"] = true,
    ["FFlagHandleAltEnterFullscreenManually"] = false,
    ["DFIntClientPacketMaxDelayMs"] = 1,
    ["FFlagUserShowGuiHideToggles"] = true,
    ["DFFlagSolverStateReplicatedOnly2"] = true,
    ["FFlagLoginPageOptimizedPngs"] = true,
    ["FFlagDebugForceFutureIsBrightPhase2"] = true,
    ["DFIntRakNetMtuValue1InBytes"] = 1280,
    ["FIntDebugForceMSAASamples"] = 0,
    ["DFIntDataSenderRate"] = 128,
    ["FFlagHighlightOutlinesOnMobile"] = true,
    ["DFIntWaitOnUpdateNetworkLoopEndedMS"] = 100,
    ["DFIntRaknetBandwidthPingSendEveryXSeconds"] = 1,
    ["DFIntMaxProcessPacketsJobScaling"] = 10000,
    ["FFlagDebugLargeReplicatorWrite"] = true,
    ["FIntNewInGameMenuPercentRollout3"] = 0,
    ["FFlagEnableInGameMenuChrome"] = true,
    ["DFIntLargePacketQueueSizeCutoffMB"] = 1000,
    ["DFFlagAllowRegistrationOfAnimationClipInCoreScripts"] = true,
    ["DFIntClientPacketExcessMicroseconds"] = 1000,
    ["FIntV1MenuLanguageSelectionFeaturePerMillageRollout"] = 0,
    ["DFIntRakNetMtuValue3InBytes"] = 1200,
    ["FFlagDebugDisableTelemetryV2Stat"] = true,
    ["DFIntMaxProcessPacketsStepsAccumulated"] = 0,
    ["FFlagLuaAppLegacyInputSettingRefactor"] = true,
    ["FFlagEnableInGameMenuDurationLogger"] = false,
    ["DFFlagReplicateCreateToPlayer"] = true,
    ["FFlagDebugDisableTelemetryEphemeralCounter"] = true,
    ["DFIntCanHideGuiGroupId"] = 32380007,
    ["FFlagDebugCodegenOptSize"] = true,
    ["FFlagDebugDisableOptimizedBytecode"] = false,
    ["DFFlagRakNetUseSlidingWindow4"] = true,
    ["FFlagDebugGraphicsPreferD3D11"] = true,
    ["FFlagEnableZstdForClientSettings"] = false,
    ["FFlagOptimizeNetwork"] = true,
    ["DFFlagReplicatorCheckReadTableCollisions"] = true,
    ["FFlagAssetImportRemoveAnimationSuffix"] = true,
    ["DFFlagRakNetUnblockSelectOnShutdownByWritingToSocket"] = true,
    ["FFlagAlwaysShowVRToggleV3"] = false,
    ["DFIntNetworkPrediction"] = 120,
    ["FFlagDebugDisableTelemetryEventIngest"] = true,
    ["FFlagDisablePostFx"] = true,
    ["DFIntBufferCompressionLevel"] = 0,
    ["DFFlagDisableDPIScale"] = false,
    ["DFIntBufferCompressionThreshold"] = 100,
    ["FFlagMessageBusCallOptimization"] = true,
    ["DFFlagRakNetEnablePoll"] = true,
    ["FFlagTaskSchedulerLimitTargetFpsTo2402"] = false,
    ["FFlagEnableInGameMenuChromeABTest4"] = true,
    ["FFlagGameBasicSettingsFramerateCap5"] = false,
    ["FIntTerrainArraySliceSize"] = 0,
    ["FFlagGraphicsFixMsaaInGuiScene"] = true,
    ["DFIntDebugSimPrimalStiffness"] = 0,
    ["DFIntGraphicsOptimizationModeMinFrameTimeTargetMs"] = 25,
    ["FFlagDebugNextGenReplicatorEnabledWriteCFrameColor"] = true,
    ["DFFlagSimSolverOptimizeLDLCache"] = true,
    ["DFFlagRakNetDetectNetUnreachable"] = true,
    ["FFlagLuauSolverV2"] = true,
    ["DFIntPlayerNetworkUpdateQueueSize"] = 20,
    ["DFFlagTextureQualityOverrideEnabled"] = true,
    ["FIntRakNetResendBufferArrayLength"] = 128,
    ["FFlagKeepZeroInfluenceBones"] = false,
    ["FFlagAddHapticsToggle"] = false,
    ["FFlagDebugDisableTelemetryV2Event"] = true,
    ["DFIntNetworkInProcessLimitGameplayMsClient"] = 0,
    ["FFlagEnableSceneAnalysis"] = false,
    ["FFlagLuaMenuPerfImprovements"] = true,
    ["DFFlagDebugRenderForceTechnologyVoxel"] = true,
    ["DFFlagReplicatorSeparateVarThresholds"] = true,
    ["DFIntRaknetBandwidthInfluxHundredthsPercentageV2"] = 10000,
    ["DFIntRakNetResendRttMultiple"] = 1,
    ["DFIntRuntimeConcurrency"] = 12,
    ["FFlagEnableAnimatorSkipCopyPreviousRigKeyOnJointModification"] = true,
    ["DFIntWaitOnRecvFromLoopEndedMS"] = 100,
    ["FFlagDebugDisableTelemetryEphemeralStat"] = true,
    ["DFIntNetworkQualityResponderMaxWaitTime"] = 1,
    ["FLogNetwork"] = 7,
    ["FIntFullscreenTitleBarTriggerDelayMillis"] = 3600000,
    ["DFIntBatchThumbnailResultsSizeCap"] = 200,
    ["FFlagReplicateAnimationLooped"] = false,
    ["FIntRenderShadowIntensity"] = 0,
    ["DFIntMaxReceiveToDeserializeLatencyMilliseconds"] = 10,
    ["FFlagDebugDisableTelemetryV2Counter"] = true,
    ["DFIntConnectingTimerInterval"] = 10,
    ["DFIntCodecMaxOutgoingFrames"] = 10000,
    ["DFFlagDebugPrintDataPingBreakDown"] = false,
    ["DFIntPerformanceControlFrameTimeMaxUtility"] = -1,
    ["DFIntOptimizePingThreshold"] = 50,
    ["DFIntNetworkQualityResponderUnit"] = 10,
    ["FFlagOptimizeNetworkTransport"] = true,
    ["DFIntServerTickRate"] = 60,
    ["FIntInterpolationMaxDelayMSec"] = 100,
    ["FFlagDebugLargeReplicatorEnabled"] = true,
    ["DFIntRakNetClockDriftAdjustmentPerPingMillisecond"] = 100,
    ["FFlagEnableInGameMenuModernization"] = true,
    ["FFlagDebugSimDefaultPrimalSolver"] = true,
    ["DFIntMaximumFreefallMoveTimeInTenths"] = 1000
}

local successCount = 0
local failCount = 0

for flag, value in pairs(FFlags) do
    if setfflag then
        local ok = pcall(function()
            setfflag(flag, value)
        end)
        if not ok then
            ok = pcall(function()
                setfflag(flag, tostring(value))
            end)
        end
        
        if ok then
            successCount = successCount + 1
        else
            failCount = failCount + 1
        end
    else
        warn("setfflag function not found in this executor environment.")
        break
    end
end
if successCount > 0 or failCount > 0 then
    print(("[FFlag Optimizer] Applied %d Fast Flags successfully, %d failed."):format(successCount, failCount))
end
